server:
  port: 8082

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin@localhost:27017/catalogdb?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
